# This is a basic workflow to help you get started with Actions

name: Request Access

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      userName:
        type: string
        required: true
        description: UserName of the Switch Tenant
      Duration:
        description: Duration of Access Required
        required: true
        type: string
      Role:
        description: Type of Role Needed
        required: true
        type: string
        options:
          - Reader
          - Contributor
      workload:
        description: Prod or Nonprod Subscription
        type: choice
        required: true
        options:
          - prod
          - nonprod

permissions:
  issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Send Email Notification
        run: echo EMAIl Send

      # Runs a set of commands using the runners shell
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: rahul-fadv
          minimum-approvals: 1
          issue-title: "Requesting ${{ inputs.Role }} on ${{ inputs.workload }} for ${{ inputs.userName }}"
          issue-body: "Please approve or deny the request of ${{ inputs.userName }} for ${{ inputs.Role }} on ${{ inputs.workload }}"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
      
      - name: Run on Approval
        run: echo Assigning Role to user

