# This is a basic workflow to help you get started with Actions

name: Request Access

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      userName:
        type: string
        required: true
        description: UserName of the Switch Tenant
      userEmail:
        type: string
        required: true
        description: UserName of the Switch Tenant
      Duration:
        description: Duration of Access Required
        required: true
        type: string
      Role:
        description: Type of Role Needed
        required: true
        type: choice
        options:
          - Reader
          - Contributor
      resourceGroup:
        description: RG Name
        required: true
        type: string
      workload:
        description: Prod or Nonprod Subscription
        type: choice
        required: true
        options:
          - prod
          - nonprod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Send Email Notification
        run: echo EMAIl Send

      - name: 'Trigger Power Automate Workflow'
        run: echo "curl 'https://prod-181.westus.logic.azure.com:443/workflows/aa1400860e384e4fbcdf163913cb4aae/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=u6DrYAlrSdyc78oU5Fe8YV9JioseYfd5JagTBHylbk8' -d '{"userName": "'"${{ inputs.userName }}"'", "userEmail": "'"${{ inputs.userEmail }}"'", "subscription": "'"${{ inputs.workload }}"'", "resourceGroup": "'"${{ inputs.resourceGroup }}"'", "roleRequested": "'"${{ inputs.Role }}"'", "duration": "'"${{ inputs.Duration }}"'"}' -X POST -H "Content-Type: application/json""
      
      - name: Run on Approval
        run: echo Assigning Role to user

