name: Switch DNS Workflow

on:
#   push:
#     branches:
#       - demo-main
#     paths:
#       - .parameters/dns/*
#       - infra-as-code/bicep/orchestration/switchDns.bicep
  pull_request:
    types:
      - opened

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: rg-fa-switch-domains
  SUBSCRIPTION_ID: 50ecff64-2bbf-4ce6-9d4d-80990843efa5

jobs:
  dns-deployment:
    runs-on: ubuntu-latest
    environment: fareimagine
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: 'Records That will be Deleted'
      run: |
        printenv
